can_ports: ["can4", "can5"]
max_current_A: 2
has_endstop: false
calibration:
    endstop_search_torques_Nm: [-0.22, -0.22, -0.22]
    position_tolerance_rad: 0.05
    move_steps: 500
safety_kd: [0.08, 0.08, 0.04]
position_control_gains:
    kp: [4, 4, 4]
    kd: [0.01, 0.01, 0.01]

# No position limits in this mode
hard_position_limits_lower: [-.inf, -.inf, -.inf]
hard_position_limits_upper: [.inf, .inf, .inf]

home_offset_rad: [0, 0, 0]
initial_position_rad: [0, 0, 0]
