can_ports: ["can0", "can1", "can2", "can3", "can4", "can5"]
max_current_A: 2.0
has_endstop: true
calibration:
    endstop_search_torques_Nm: 
        - +0.22
        - +0.22
        - -0.22
        - +0.22
        - +0.22
        - -0.22
        - +0.22
        - +0.22
        - -0.22
    position_tolerance_rad: 0.05
    move_timeout: 2000
safety_kd:
    - 0.09
    - 0.09
    - 0.05
    - 0.09
    - 0.09
    - 0.05
    - 0.09
    - 0.09
    - 0.05
position_control_gains:
    kp: [6, 6, 6, 6, 6, 6, 6, 6, 6]
    kd: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03]

hard_position_limits_lower: [-5, -5, -5, -5, -5, -5, -5, -5, -5]
hard_position_limits_upper: [5, 5, 5, 5, 5, 5, 5, 5, 5]

# Set zero-position according to URDF (finger pointing straight down).
home_offset_rad:
    - -2.12
    - -2.44
    - 2.16
    - -1.6
    - -2.16
    - 2.58
    - -2.01
    - -2.14
    - 2.57

# Set the initial position such that it is still save when the stage is at the
# highest level.
initial_position_rad:
    - 0
    - 0.9
    - -1.7
    - 0
    - 0.9
    - -1.7
    - 0
    - 0.9
    - -1.7

