can_ports: ["can0", "can1", "can2", "can3", "can4", "can5"]
max_current_A: 2.0
has_endstop: true
calibration:
    endstop_search_torques_Nm: 
        - +0.22
        - +0.22
        - -0.22
        - +0.22
        - +0.22
        - -0.22
        - +0.22
        - +0.22
        - -0.22
    position_tolerance_rad: 0.05
    move_steps: 500
safety_kd:
    - 0.09
    - 0.09
    - 0.05
    - 0.09
    - 0.09
    - 0.05
    - 0.09
    - 0.09
    - 0.05
position_control_gains:
    kp: [4, 4, 4, 4, 4, 4, 4, 4, 4]
    kd: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]


#hard_position_limits_lower: [-.inf, -.inf, -.inf, -.inf, -.inf, -.inf, -.inf, -.inf, -.inf]
#hard_position_limits_upper: [.inf, .inf, .inf, .inf, .inf, .inf, .inf, .inf, .inf]

hard_position_limits_lower:
    - -1.0
    - -1.67
    - -2.8
    - -1.0
    - -1.67
    - -2.8
    - -1.0
    - -1.67
    - -2.7
hard_position_limits_upper:
    - 1.5
    - 1.67
    - 2.8
    - 1.5
    - 1.67
    - 2.8
    - 1.5
    - 1.67
    - 2.8

soft_position_limits_lower:
    - -0.9
    - -1.57
    - -2.7
    - -0.9
    - -1.57
    - -2.7
    - -0.9
    - -1.57
    - -2.7
soft_position_limits_upper:
    - 1.4
    - 1.57
    - 2.7
    - 1.4
    - 1.57
    - 2.7
    - 1.4
    - 1.57
    - 2.7

# Prototype platform (1)
#home_offset_rad: [-1.876, -1.877,  2.368, -1.633, -1.825,  2.045, -2.158, -2.215,  2.133]

# platform 2
#home_offset_rad: [-1.681, -2.251,  2.039, -1.975, -1.855,  2.233, -1.651, -2.447,  2.057]

# Platform 3
#home_offset_rad:
#    - -2.02
#    - -2.37
#    - 2.12
#    - -2.06
#    - -2.23
#    - 2.08
#    - -1.58
#    - -2.18
#    - 2.19

# platform 4
home_offset_rad: [-1.744, -2.233,  2.611, -1.659, -2.346,  2.677, -2.127, -2.463,  2.597]


# Set the initial position such that it is still save when the stage is at the
# highest level.
initial_position_rad:
    - 0
    - 0.9
    - -1.7
    - 0
    - 0.9
    - -1.7
    - 0
    - 0.9
    - -1.7

