can_ports: ["can0", "can1", "can2", "can3", "can4", "can5"]
max_current_A: 2.0
has_endstop: true
calibration:
    endstop_search_torques_Nm: 
        - +0.22
        - +0.22
        - -0.22
        - +0.22
        - +0.22
        - -0.22
        - +0.22
        - +0.22
        - -0.22
    position_tolerance_rad: 0.05
    move_timeout: 2000

safety_kd:
    - 0.04
    - 0.04
    - 0.02
    - 0.04
    - 0.04
    - 0.02
    - 0.04
    - 0.04
    - 0.02

#safety_kd:
#    - 0.08
#    - 0.08
#    - 0.08
#    - 0.08
#    - 0.08
#    - 0.08
#    - 0.08
#    - 0.08
#    - 0.08

position_control_gains:
    kp: [6, 6, 6, 6, 6, 6, 6, 6, 6]
    #kd: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03]
    kd: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]


#hard_position_limits_lower: [-.inf, -.inf, -.inf, -.inf, -.inf, -.inf, -.inf, -.inf, -.inf]
#hard_position_limits_upper: [.inf, .inf, .inf, .inf, .inf, .inf, .inf, .inf, .inf]

hard_position_limits_lower:
    - -1.9
    - 0.5
    - -3.4
    - -1.9
    - 0.5
    - -3.4
    - -1.9
    - 0.5
    - -3.4
hard_position_limits_upper:
    - 1.9
    - 1.9
    - -1.3
    - 1.9
    - 1.9
    - -1.3
    - 1.9
    - 1.9
    - -1.3

# Set zero-position according to URDF (finger pointing straight down).
home_offset_rad:
    - -1.903
    - -1.845
    - 2.242
    - -1.616
    - -1.762
    - 1.996
    - -2.148
    - -2.143
    - 2.152

# Set the initial position such that it is still save when the stage is at the
# highest level.
initial_position_rad:
    - 0
    - 0.9
    - -1.7
    - 0
    - 0.9
    - -1.7
    - 0
    - 0.9
    - -1.7

